# -*- coding: utf-8 -*-
"""4110012018_HW2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ky1fRD35pNO2mMXc-h57Py550eyYhKvN
"""

def memory_addressing(page_table, page_size, logical_address):
  page_number, offset = divmod(logical_address, page_size)
  if page_number in page_table:
    frame_number = page_table[page_number]
    physical_address = frame_number * page_size + offset
    print(f"The physical_address is {physical_address}")
  else:
    print("invalid page number, address translation failed.")

page_table = {0:5,
              1:9,
              2:14}
page_size=4096
logical_address = int(input("Enter the logical address: "))


memory_addressing(page_table, page_size, logical_address)